#!/bin/sh
usage() {
    printf "Usage: pdfless [-h] <browser|url-opener> [<file>]\nArguments:\
            \n\tbrowser|url-opener: A browser (e.g. \`firefox\`) or URL opener\
            \n\t(e.g. \`xdg-open\`) to open the <file>.\n" 1>&2;
}
cmd_exist() {
    command -v "$@" >/dev/null 2>&1
}
get_path() {
    if [ -h "$1" ]; then
        dirname "$(readlink "$1")"
    else
        dirname "$1"
    fi
}
start_server() {
    if cmd_exist python3; then
        serve="python3 -m http.server $1"
    elif cmd_exist python2; then
        serve="python2 -m SimpleHTTPServer $1"
    elif cmd_exist ruby; then
        serve="ruby -run -e httpd . -p $1"
    elif cmd_exist php; then
        serve="php -S localhost:$1"
    else
        echo "pdfless: Cannot run server."
        exit 1
    fi
    cd "$2" >/dev/null 2>&1 || exit
    $serve >/dev/null 2>&1 &
    trap "rm -rf tmp >/dev/null 2>&1; kill $!" EXIT
    trap "exit 0" INT TERM
    echo "pdfless: Server running at localhost:$1. ^C to quit."
    sleep 1
}

while getopts "h" o; do
    case "$o" in
        h)
            usage
            exit 0
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "$1" ] || ! cmd_exist "$1"; then
    usage
    exit 1
fi
exepath="$(get_path "$0")"
mkdir -p "$exepath/tmp" || exit
if [ -n "$2" ]; then
    if ! [ -f "$2" ]; then
        echo "pdfless: No such file: $2"
        exit 1
    else
        cp "$2" "$exepath/tmp/" || exit
        fname="$(basename "$2")"
        fpath="../tmp/$fname"
        echo "pdfless: Opening $fname in $1..."
    fi
fi

port=60656  # Random port in private range
nc -z localhost $port >/dev/null 2>&1 || start_server $port "$exepath"
$1 "http://localhost:$port/web/viewer.html?enc=false&file=$fpath"
wait
